spring:
  application:
    name: elastic-search-practice
  data:
    elasticsearch:
      repositories:
        enabled: false
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:book_search}
    username: ${POSTGRES_USER:jeonjaeyeon}
    password: ${POSTGRES_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://localhost:9200}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org.hibernate.SQL: debug
